version: '3.7'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 10096:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - AWS_ACCESS_KEY_ID=AKIAJTZE5VSYTWEOWB5Q
      - AWS_SECRET_ACCESS_KEY=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
      - REGION_NAME=us-east-1